export * from "./use-departments";
export * from "./use-halls";
export * from "./use-students";
export * from "./use-doctors";
export * from "./use-courses";
export * from "./use-lectures";
export * from "./use-attendance";
export * from "./use-settings";
export * from "./use-dashboard";
