name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # ادخل المسار الصحيح هنا
            PROJECT_PATH="/home/${{ secrets.SERVER_USER }}/graduation-project"
            
            if [ ! -d "$PROJECT_PATH" ]; then
              echo "Project directory not found. Cloning for the first time..."
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git "$PROJECT_PATH"
              cd "$PROJECT_PATH"
            else
              cd "$PROJECT_PATH"
              git fetch --all
              git reset --hard origin/main
            fi

            
            # إنشاء ملف الـ .env من الـ Secrets
            echo "${{ secrets.BACKEND_ENV }}" > "$PROJECT_PATH/backend/.env"
            
            # تشغيل الـ Docker
            sudo docker-compose -f docker-compose.deploy.yml up -d --build
            sudo docker system prune -f
